import meal1 from "./images/meal1.jpeg";
import meal2 from "./images/meal2.jpeg";
import meal3 from "./images/meal3.jpeg";
import meal4 from "./images/meal4.jpeg";
import meal5 from "./images/meal5.jpeg";
const MealsData = [
  {
    id: "1",
    name: "Kamat Restaurant - Mankool Bur Dubai",
    city: "Next to Gazebo Restaurant, Al Mankhool Road - Dubai - U.A.E",
    freeCancel: "24 ",
    instentConfirm: true,
    nearHotel: ["Leva-Mazaya-Centre", "	Villa-Rotana-Dubai"],
    veg: true,
    nonVeg: false,
    jainMeals: true,
    standerdType: "Standard",
    fecilitiys: "Buffett Dinner Live Music",
    description:
      "We will be provided Indian cuisine at Bengre Kamat. Being at this place, degust nicely cooked turkey, paneer and upma. To taste good pancakes is a really good idea. Great coffee is served - try and enjoy.",
    Inclusion: [
      "Dry Veg (S.I)",
      "Curry Veg.(S.I)",
      "Jeera Aloo",
      "Chana Masala",
    ],
    usefulInfo: [
      "MEALS ONLY / COUPON / VOUCHER / TOKEN or Similar: stands for meals without transfer",
      "VEG & NON VEG MEALS Stands for a restaurant where cocked both Veg & Non Veg.",
      "PURE VEG Stands for a restaurant where cocked only Veg & Jain Meals",
      " PURE VEG Means food without onion, garlic & root vegetables, ensure to update to your agent.",
    ],
    termsAndCOnditions: [
      "We reserve the complete right to change restaurant or offer similar restaurant at same location if in case restaurant unable to accommodate due to last moment booking or any festival rush, or even cancel or refund against the meals.",
      "Most of restaurants have specific time for lunch / dinner & opening & closing time. Any guest failing to reach on time or non-availability at designated restaurant will be considered a no-show. No reimbursement or alternative meals will be arranged in such circumstances.",
    ],
    Timing: "10:30 AM to 03:15 PM & 07:00 PM to 12:00 AM",
    price: "27",
    ourPrice: "25",
    img: meal1,
    tktList: [
      {
        ticketTypeId: 10,
        b2bAdultPrice: 250,
        b2bChildPrice: 0,
        ttTicketType: "Breakfast (South Indian)",
        transport: [
          {
            sharedOrPrivate: 0,
            transportId: 0,
            transportName: "Without Transport",
            cost: 0,
            ticketTypeId: 10,
            b2bAdultPrice: 250,
            b2bChildPrice: 0,
            transportCat: "",
          },
          {
            sharedOrPrivate: 1,
            transportId: 1,
            transportName: "With Transfer",
            cost: 70,
            ticketTypeId: 10,
            b2bAdultPrice: 250,
            b2bChildPrice: 0,
            transportCat: "",
          },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "Aaramam Restaurant Rolla Road",
    city: "Mostafa Bin Abdullatif - Raffa Building , Back ride palm beach hotel",
    freeCancel: "24 ",
    instentConfirm: true,
    nearHotel: [],
    veg: true,
    nonVeg: true,
    jainMeals: false,
    standerdType: "Standard",
    fecilitiys: " Unlimited Set Meals",
    description:
      "Our story routes back to a little boy spending time in the kitchen watching other people cook and pound some flavourful masalas. With the growing numbers in Konaar mess, grew his growing passion. Mr Anjappan started off with his first restaurant located in Royapettah, Chennai in the year 1964 with the blessings of Sri M G Ramachandran, a well-renowned actor. Starting off with a single outlet to now serving 48 outlets in India and over 35 outlets spread across 25 countries, we are proud to call ourselves the world’s largest chain of Chettinad Restaurants.",
    Inclusion: [
      "Dry Veg (S.I)",
      "Curry Veg.(S.I)",
      "Jeera Aloo",
      "Chana Masala",
    ],
    usefulInfo: [
      "MEALS ONLY / COUPON / VOUCHER / TOKEN or Similar: stands for meals without transfer",
      "VEG & NON VEG MEALS Stands for a restaurant where cocked both Veg & Non Veg.",
      "PURE VEG Stands for a restaurant where cocked only Veg & Jain Meals",
      " PURE VEG Means food without onion, garlic & root vegetables, ensure to update to your agent.",
    ],
    termsAndCOnditions: [
      "We reserve the complete right to change restaurant or offer similar restaurant at same location if in case restaurant unable to accommodate due to last moment booking or any festival rush, or even cancel or refund against the meals.",
      "Most of restaurants have specific time for lunch / dinner & opening & closing time. Any guest failing to reach on time or non-availability at designated restaurant will be considered a no-show. No reimbursement or alternative meals will be arranged in such circumstances.",
    ],
    Timing: " Lunch : 10:30 AM to 03:15 PM & Dinner: 07:00 PM to 12:00 AM",
    price: "35",
    ourPrice: "30",
    img: meal2,
    tktList: [
      {
        ticketTypeId: 7,
        b2bAdultPrice: 100,
        b2bChildPrice: 0,
        ttTicketType: "North Indian Lunch Thali",
        transport: [
          {
            sharedOrPrivate: 0,
            transportId: 0,
            transportName: "Without Transport",
            cost: 0,
            ticketTypeId: 7,
            b2bAdultPrice: 100,
            b2bChildPrice: 0,
            transportCat: "",
          },
          {
            sharedOrPrivate: 1,
            transportId: 1,
            transportName: "With Transport",
            cost: 70,
            ticketTypeId: 7,
            b2bAdultPrice: 100,
            b2bChildPrice: 0,
            transportCat: "",
          },
        ],
      },
      {
        ticketTypeId: 8,
        b2bAdultPrice: 60,
        b2bChildPrice: 0,
        ttTicketType: "Breakfast",
        transport: [
          {
            sharedOrPrivate: 0,
            transportId: 0,
            transportName: "Without Transport",
            cost: 0,
            ticketTypeId: 8,
            b2bAdultPrice: 60,
            b2bChildPrice: 0,
            transportCat: "",
          },
          {
            sharedOrPrivate: 1,
            transportId: 1,
            transportName: "With Tranport",
            cost: 70,
            ticketTypeId: 8,
            b2bAdultPrice: 60,
            b2bChildPrice: 0,
            transportCat: "",
          },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "Claypot - Citymax Bur Dubai",
    city: "Citymax Bur Dubai Al Mankhool - Dubai",
    freeCancel: "24 ",
    instentConfirm: true,
    nearHotel: [
      "Al-Khoory-Executive-Hotel-Al-Wasl",
      "Lemon-Tree-Hotel-Dubai",
      "Leva-Mazaya-Centre",
      "	Villa-Rotana-Dubai",
      "Al-Khoory-Executive-Hotel-Al-Wasl",
    ],
    veg: true,
    nonVeg: true,
    jainMeals: false,

    standerdType: "Delux",
    fecilitiys: " Unlimited Set Meals",
    description:
      "We serve mouthwatering traditional Desi food, the warmth of which is reflected in our ever-smiling team ready to delight you throughout your dining experience",
    Inclusion: [
      "Dry Veg (S.I)",
      "Curry Veg.(S.I)",
      "Jeera Aloo",
      "Chana Masala",
    ],
    usefulInfo: [
      "MEALS ONLY / COUPON / VOUCHER / TOKEN or Similar: stands for meals without transfer",
      "VEG & NON VEG MEALS Stands for a restaurant where cocked both Veg & Non Veg.",
      "PURE VEG Stands for a restaurant where cocked only Veg & Jain Meals",
      " PURE VEG Means food without onion, garlic & root vegetables, ensure to update to your agent.",
    ],
    termsAndCOnditions: [
      "We reserve the complete right to change restaurant or offer similar restaurant at same location if in case restaurant unable to accommodate due to last moment booking or any festival rush, or even cancel or refund against the meals.",
      "Most of restaurants have specific time for lunch / dinner & opening & closing time. Any guest failing to reach on time or non-availability at designated restaurant will be considered a no-show. No reimbursement or alternative meals will be arranged in such circumstances.",
    ],
    Timing: " Lunch : 10:30 AM to 03:15 PM & Dinner: 07:00 PM to 12:00 AM",
    price: "80",
    ourPrice: "60",
    img: meal3,
    tktList: [],
  },
  {
    id: "4",
    name: "Bengre Kamat Restaurant - Bur Dubai",
    city: "Dolphin Hotel Apartment , Khaleed Bin Waleed Road Bur Dubai",
    freeCancel: "24 ",
    instentConfirm: true,
    nearHotel: [
      "Al-Khoory-Executive-Hotel-Al-Wasl",
      "Lemon-Tree-Hotel-Dubai",
      "Leva-Mazaya-Centre",
      "	Villa-Rotana-Dubai",
      "Al-Khoory-Executive-Hotel-Al-Wasl",
    ],
    veg: true,
    nonVeg: true,
    jainMeals: false,

    standerdType: "Luxury",
    fecilitiys: " Unlimited Set Meals",
    description:
      "A boom in hospitality sector is a boom in the tourism industry. For its part, Khamas Group has utilized its management prowess in the promotion of the local tourism industry, by maintaining spa and wellness centers, entertainment holes, and restaurants.",
    Inclusion: [
      "Dry Veg (S.I)",
      "Curry Veg.(S.I)",
      "Jeera Aloo",
      "Chana Masala",
    ],
    usefulInfo: [
      "MEALS ONLY / COUPON / VOUCHER / TOKEN or Similar: stands for meals without transfer",
      "VEG & NON VEG MEALS Stands for a restaurant where cocked both Veg & Non Veg.",
      "PURE VEG Stands for a restaurant where cocked only Veg & Jain Meals",
      " PURE VEG Means food without onion, garlic & root vegetables, ensure to update to your agent.",
    ],
    termsAndCOnditions: [
      "We reserve the complete right to change restaurant or offer similar restaurant at same location if in case restaurant unable to accommodate due to last moment booking or any festival rush, or even cancel or refund against the meals.",
      "Most of restaurants have specific time for lunch / dinner & opening & closing time. Any guest failing to reach on time or non-availability at designated restaurant will be considered a no-show. No reimbursement or alternative meals will be arranged in such circumstances.",
    ],
    Timing: " Lunch : 10:30 AM to 03:15 PM & Dinner: 07:00 PM to 12:00 AM",
    price: "35",
    ourPrice: "25",
    img: meal4,
    tktList: [],
  },
  {
    id: "5",
    name: "Sangeetha Vegetarian Restaurant - Meena Bazar",
    city: "G Floor, Near Astoria Hotel Meena Bazar - Bur Dubai",
    freeCancel: "24 ",
    instentConfirm: true,
    nearHotel: [
      "Al-Khoory-Executive-Hotel-Al-Wasl",
      "Lemon-Tree-Hotel-Dubai",
      "Leva-Mazaya-Centre",
      "	Villa-Rotana-Dubai",
      "Al-Khoory-Executive-Hotel-Al-Wasl",
    ],
    veg: true,
    nonVeg: false,
    jainMeals: true,

    standerdType: "Premium",
    fecilitiys: " Unlimited Set Meals",
    description:
      "I was pleasantly surprised when waiting for the food here. The paper masala dosa was huge and crisp and the potatoes were delicious. I am rather fussy with sambar and this one had the right amount of masala and was flavoursome. I would definitely recommend this restaurant to anyone looking to eat dosa in the area and I will be returning again for sure in the near future",
    Inclusion: [
      "Dry Veg (S.I)",
      "Curry Veg.(S.I)",
      "Jeera Aloo",
      "Chana Masala",
    ],
    usefulInfo: [
      "MEALS ONLY / COUPON / VOUCHER / TOKEN or Similar: stands for meals without transfer",
      "VEG & NON VEG MEALS Stands for a restaurant where cocked both Veg & Non Veg.",
      "PURE VEG Stands for a restaurant where cocked only Veg & Jain Meals",
      " PURE VEG Means food without onion, garlic & root vegetables, ensure to update to your agent.",
    ],
    termsAndCOnditions: [
      "We reserve the complete right to change restaurant or offer similar restaurant at same location if in case restaurant unable to accommodate due to last moment booking or any festival rush, or even cancel or refund against the meals.",
      "Most of restaurants have specific time for lunch / dinner & opening & closing time. Any guest failing to reach on time or non-availability at designated restaurant will be considered a no-show. No reimbursement or alternative meals will be arranged in such circumstances.",
    ],
    Timing: " Lunch : 10:30 AM to 03:15 PM & Dinner: 07:00 PM to 12:00 AM",
    price: "100",
    ourPrice: "90",
    img: meal5,
    tktList: [],
  },
];

export default MealsData;
